name: Eslint

on:
  pull_request:
    branches-ignore:
      - master
  push:
    branches-ignore:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Установка зависимостей
        run: npm ci
      - name: Линтинг
        run: npm run eslint
